# ====================================================================
# İŞ AKIŞI 1: VERİ İNDİRME OTOMASYONU (Optimize Edilmiş)
# ====================================================================
name: 1 - Ham Veri İndirme

on:
  schedule:
    - cron: '0 7 * * *'
  
  workflow_dispatch:

jobs:
  download-raw-data:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4
        # ❗️ DÜZELTME 1: 'fetch-depth: 0' kaldırıldı. Bu, klonlama işlemini hızlandıracak.

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Chrome Tarayıcı ve Sürücü Kurulumu
        uses: browser-actions/setup-chrome@v1
      - name: ChromeDriver Kurulumu
        uses: nanasess/setup-chromedriver@v2

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dosyaları İndir (update_list.py)
        id: run_downloader
        run: python update_list.py

      - name: Ham Veri Değişikliklerini Depoya Gönder
        if: steps.run_downloader.outputs.updated == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ham_veriler/
          git commit -m "Otomatik Ham Veri Güncellemesi: ${{ steps.run_downloader.outputs.summary }}"
          # ❗️ DÜZELTME 2: 'git pull' yerine 'git push --force' kullanıyoruz.
          # Bu, repoyu indirme ihtiyacını ortadan kaldırır.
          git push --force
