# ====================================================================
# İŞ AKIŞI 2: VERİ İŞLEME VE TEMİZLEME OTOMASYONU
# Görevi: 'ham_veriler' klasöründeki Excel dosyalarını işler, temizler
# ve 'islenmis_veriler' klasörüne JSONL olarak kaydeder.
# ====================================================================
name: 2 - Veri İşleme ve Temizleme

on:
  # Bu workflow'un, "1 - Ham Veri İndirme" workflow'u başarıyla 
  # tamamlandığında otomatik olarak tetiklenmesini sağlar.
  workflow_run:
    workflows: ["1 - Ham Veri İndirme"]
    types:
      - completed
  
  # Ayrıca manuel olarak da çalıştırılabilir.
  workflow_dispatch:

jobs:
  clean-and-process-data:
    # Sadece bir önceki workflow başarılı olduysa çalışır.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Verileri Temizle (data_cleaner.py)
        id: run_cleaner
        run: python data_cleaner.py

      - name: İşlenmiş Veri Değişikliklerini Depoya Gönder
        run: |
          # Sadece işlenmiş verilerde bir değişiklik varsa commit at
          git add islenmis_veriler/
          git diff --quiet --exit-code --cached || (git config --global user.name 'github-actions[bot]' && git config --global user.email 'github-actions[bot]@users.noreply.github.com' && git commit -m "Otomatik İşlenmiş Veri Güncellemesi" && git pull --rebase && git push)
