# Dosya Yolu: .github/workflows/main.yml (Nihai Çalışma Sürümü)

name: Veri Temizleme Otomasyonu

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: write

jobs:
  clean-data:
    runs-on: ubuntu-latest
    name: Veri Dosyalarını Temizle ve Güncelle

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python 3.9 Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Bağımlılıkları Yükle
        run: pip install pandas openpyxl
      
      - name: Verileri Temizle (data_cleaner.py)
        run: python data_cleaner.py

      - name: Değişiklikleri Depoya Gönder
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add islenmis_veriler/
          if [[ -z $(git status --porcelain) ]]; then
            echo "İşlenmiş verilerde herhangi bir değişiklik bulunamadı."
          else
            TODAY=$(date -u +"%Y-%m-%d")
            git commit -m "Otomatik Veri Temizleme: $TODAY"
            git push
          fi