# Dosya Yolu: .github/workflows/main.yml (İzinler Düzeltilmiş Nihai Sürüm)

name: Veri Temizleme Otomasyonu

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

# --- YENİ EKLENEN İZİN BLOĞU ---
# Bu blok, iş akışına deponun içeriğini değiştirme (yazma) yetkisi verir.
permissions:
  contents: write
# ---------------------------------

jobs:
  clean-data:
    runs-on: ubuntu-latest
    name: Veri Dosyalarını Temizle ve Güncelle

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python 3.9 Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Bağımlılıkları Yükle
        # requirements.txt dosyanızın sadece pandas ve openpyxl içerdiğini varsayıyoruz
        run: pip