# Dosya Yolu: .github/workflows/main.yml

name: TİTCK Veri Otomasyonu

on:
  schedule:
    - cron: '0 3 * * *' # Her gün UTC 03:00'da çalışır
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python 3.9 Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Playwright Tarayıcılarını Kur
        run: playwright install --with-deps

      - name: 1. Adım - Şifreli Fiyat Listesini İndir
        env:
          TITCK_USERNAME: ${{ secrets.TITCK_USERNAME }}
          TITCK_PASSWORD: ${{ secrets.TITCK_PASSWORD }}
        run: python downloader.py
      
      # KULLANICI NOTU: Diğer halka açık dosyaları da indirmek için
      # benzer bir public_downloader.py betiği oluşturup buraya ekleyebilirsiniz.

      - name: 2. Adım - Tüm Ham Verileri Temizle
        run: python data_cleaner.py

      - name: 3. Adım - İşlenmiş Verileri Depoya Gönder
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add islenmis_veriler/
          if [[ -z $(git status --porcelain) ]]; then
            echo "İşlenmiş verilerde herhangi bir değişiklik bulunamadı."
          else
            TODAY=$(date -u +"%Y-%m-%d")
            git commit -m "Otomatik Veri Güncelleme: $TODAY"
            git push
          fi