# Dosya Yolu: .github/workflows/main.yml
# Ana veri indirme ve temizleme iş akışı

name: Veri İndirme ve Temizleme Otomasyonu

on:
  # Manuel olarak da çalıştırabilmek için
  workflow_dispatch:
  # Zamanlanmış görev (isteğe bağlı, isterseniz bu bölümü silebilirsiniz)
  schedule:
    - cron: '0 4 * * *' # Her gün UTC 04:00'da çalışır

permissions:
  contents: write

jobs:
  update-and-clean:
    runs-on: ubuntu-latest
    name: Verileri İndir, Temizle ve Kaydet
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Bağımlılıkları Yükle
        run: python -m pip install -r requirements.txt
      
      - name: Adım 1 - Dosyaları İndir (update_list.py)
        run: python update_list.py
      
      - name: Adım 2 - Verileri Temizle (data_cleaner.py)
        run: python data_cleaner.py

      - name: Adım 3 - Değişiklikleri Depoya Gönder
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Hem indirilen ham veriyi hem de işlenmiş veriyi depoya kaydet
          git add islenmis_veriler/ ham_veriler/
          if [[ -z $(git status --porcelain) ]]; then
            echo "Yeni veya güncellenmiş veri bulunamadı."
          else
            TODAY=$(date -u +"%Y-%m-%d")
            git commit -m "Otomatik Veri Güncelleme ve Temizleme: $TODAY"
            git push
          fi
