# Dosya Yolu: .github/workflows/main.yml

name: TİTCK Veri Otomasyonu (Self-Hosted Runner)

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: self-hosted

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python 3.9 Ortamını Ayarla
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Bağımlılıkları Yükle (requirements.txt)
        run: python -m pip install -r requirements.txt
        shell: bash # Bu ve sonraki basit komutlar için bash kullanmak daha tutarlı olabilir
        
      - name: Playwright Tarayıcılarını Kur
        run: python -m playwright install --with-deps
        shell: bash

      - name: Adım 1 - Güvenli Dosyayı İndir (downloader.py)
        id: download_step
        env:
          TITCK_USERNAME: ${{ secrets.TITCK_USERNAME }}
          TITCK_PASSWORD: ${{ secrets.TITCK_PASSWORD }}
        run: python downloader.py
        shell: bash

      - name: Hata Durumunda Ekran Görüntüsünü Yükle
        if: failure() && steps.download_step.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: hata-ekran-goruntusu
          path: debug_screenshot.png
      
      - name: Adım 2 - Verileri Temizle (data_cleaner.py)
        run: python data_cleaner.py
        shell: bash

      # --- DÜZELTİLEN ADIM BURASI ---
      - name: Adım 3 - Değişiklikleri Depoya Gönder (Commit & Push)
        # Windows runner'ı varsayılan olarak PowerShell kullandığı için
        # bu adımı PowerShell sözdiziminde yazıyoruz.
        shell: powershell
        run: |
          # Git için bot kimliğini yapılandır
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Sadece 'islenmis_veriler' klasöründeki değişiklikleri ekle
          git add islenmis_veriler/
          
          # Değişiklik olup olmadığını kontrol et
          $gitStatus = git status --porcelain
          
          if ([string]::IsNullOrWhiteSpace($gitStatus)) {
              # Eğer değişiklik yoksa, mesaj yaz ve çık
              Write-Host "İşlenmiş verilerde herhangi bir değişiklik bulunamadı."
          } else {
              # Değişiklik varsa, commit at ve gönder
              Write-Host "Değişiklikler bulundu, commit atılıyor ve gönderiliyor..."
              $TODAY = Get-Date -UFormat "%Y-%m-%d"
              git commit -m "Otomatik Veri Güncelleme (Self-Hosted): $TODAY"
              git push
          }