# Dosya Yolu: .github/workflows/main.yml (GEÇİCİ TEŞHİS SÜRÜMÜ)

name: Veri Temizleme - TEŞHİS MODU

on: [push, workflow_dispatch]

jobs:
  diagnose-file:
    runs-on: ubuntu-latest
    name: Excel Dosyasını İncele

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python 3.9 Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Bağımlılıkları Yükle
        run: pip install pandas openpyxl

      - name: Excel Dosyasının Yapısını Yazdır
        run: python diagnose_excel.py ham_veriler/ilac_fiyat_listesi.xlsx