name: TİTCK İlaç Listesi Güncelleyici

on:
  # Zamanlanmış görev: Her gün sabah 10:00 ve akşam 22:00'de (UTC+3) çalışır.
  # Cron zamanlaması UTC'ye göredir. Türkiye saati (UTC+3) için 3 saat geri alınır.
  # 07:00 UTC -> 10:00 TR, 19:00 UTC -> 22:00 TR
  schedule:
    - cron: '0 7,19 * * *'
  
  # Manuel çalıştırma: GitHub arayüzündeki "Actions" sekmesinden manuel olarak tetiklemeyi sağlar.
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Adım: Repoyu Klonla
      # Action'ın çalışacağı sanal makineye repodaki kodları çeker.
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Adım: Python Ortamını Kur
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Kullanmak istediğiniz Python sürümü
          cache: 'pip' # Bağımlılıkları cache'leyerek sonraki çalışmaları hızlandır

      # 3. Adım: Python Bağımlılıklarını Yükle
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas openpyxl

      # 4. Adım: Güncelleme Script'ini Çalıştır
      - name: Run update script
        id: run_script # Bu adıma bir ID veriyoruz ki çıktısını kullanabilelim
        run: python update_list.py

      # 5. Adım: Değişiklikleri Repoya Commit'le ve Push'la
      # Bu adım, SADECE bir güncelleme olduğunda çalışır.
      # `run_script` adımının 'updated' çıktısı 'true' ise bu adım tetiklenir.
      - name: Commit and push if files changed
        if: steps.run_script.outputs.updated == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/
          # Commit mesajına güncel tarihi ekleyelim
          git commit -m "Veri Güncellemesi: $(date +'%Y-%m-%d %H:%M:%S')"
          git push