# Workflow'un Adı: GitHub Actions arayüzünde görünecek olan isim.
name: TİTCK İlaç Listesi Güncelleyici

# Workflow'u Tetikleyecek Olaylar:
on:
  schedule:
    # Her gün 10:00 ve 22:00 (TSİ) çalışır.
    - cron: '0 7,19 * * *'
  
  workflow_dispatch:

# Workflow'un İşleri (Jobs):
jobs:
  update-data:
    runs-on: ubuntu-latest
    
    # ❗️ YENİ EKLENEN İZİN BLOKU ❗️
    # Bu blok, GITHUB_TOKEN'a deponun içeriğini yazma izni verir.
    permissions:
      contents: write
    
    # İşin Adımları (Steps):
    steps:
      # Adım 1: Repoyu Klonla
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Adım 2: Python Ortamını Kur
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # Adım 3: Python Bağımlılıklarını Yükle
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Adım 4: Güncelleme Script'ini Çalıştır
      - name: Run update script
        id: run_script
        run: python update_list.py

      # Adım 5: Değişiklikleri Repoya Yükle
      - name: Commit and push if files changed
        if: steps.run_script.outputs.updated == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/
          git commit -m "Otomatik Veri Güncellemesi: $(date +'%Y-%m-%d %H:%M:%S')"
          git push