# .github/workflows/update_checker.yml
name: TİTCK Güncelleme Kontrolü

on:
  schedule:
    # Her 6 saatte bir çalışır (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: {}

permissions:
  issues: write      # Issue açma izni
  contents: write    # last_known_links.json güncelleme izni

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    name: Kaynak Dosyaları Kontrol Et
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Bağımlılıkları Yükle
        run: python -m pip install -r requirements.txt

      - name: Güncellemeleri Kontrol Et (update_checker.py)
        id: checker
        run: python update_checker.py

      - name: Değişiklik Varsa Bildirim Oluştur
        if: steps.checker.outputs.is_updated == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '📢 TİTCK Verilerinde Güncelleme Tespit Edildi!',
              body: `TİTCK kaynak dosyalarında yeni bir versiyon bulundu.
              Değişen dosyalar: ${{ steps.checker.outputs.changed_files }}`
            })

      - name: Güncel Dosya Durumunu Depoya İşle
        if: steps.checker.outputs.is_updated == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add last_known_links.json
          git commit -m "Otomatik: Dosya link durumunu güncelle"
          git push
