name: TİTCK Veri Listeleri Güncelleyici

on:
  schedule:
    # Her gün sabah 10:00 ve akşam 22:00 (TSİ) çalışır.
    - cron: '0 7,19 * * *'
  
  # Manuel çalıştırmayı sağlar
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    permissions:
      # Repoya yazma izni verir
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      # DEĞİŞİKLİK 1: Bu adıma bir ID ("setup_chrome") veriyoruz.
      - name: Setup Chrome
        id: setup_chrome 
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # DEĞİŞİKLİK 2: env bloğunu, bir önceki adımın çıktısını kullanacak şekilde düzeltiyoruz.
      - name: Run update script
        id: run_script
        env:
          TITCK_USERNAME: ${{ secrets.TITCK_USERNAME }}
          TITCK_PASSWORD: ${{ secrets.TITCK_PASSWORD }}
          # 'setup_chrome' adımının 'chrome-driver' çıktısını ortam değişkeni olarak ata.
          CHROME_DRIVER_PATH: ${{ steps.setup_chrome.outputs.chrome-driver }}
        run: python update_list.py

      - name: Commit and push if files changed
        if: steps.run_script.outputs.updated == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Artık data klasöründeki her şeyi ekliyoruz (.png'ler dahil)
          git add ham_veriler/
          git commit -m "${{ steps.run_script.outputs.summary }}"
          git pull --rebase
          git push
