name: TİTCK Veri Listeleri Güncelleyici

on:
  schedule:
    - cron: '0 7,19 * * *'
  
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        id: run_script
        run: python update_list.py

      # Commit mesajı artık Python script'inden gelen 'summary' çıktısını kullanıyor.
      - name: Commit and push if files changed
        if: steps.run_script.outputs.updated == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/
          git commit -m "${{ steps.run_script.outputs.summary }}"
          git push